Repository nats-io/nats-server, pull requests merged in 2018-03, with the labels that each got.

#641 [FIXED] RACE in Sublist
  server/sublist.go
  server/sublist_test.go
Labels: bug

#615 [ADDED] Monitor endpoints as server methods (Varz(), etc..)
  server/monitor.go
  server/monitor_sort_opts.go
  server/monitor_test.go
Labels: customer requested, enhancement, monitoring

#638 [IMPROVED] Better attempt at delivering messages to queue subscriptions
  server/client.go
  server/route.go
  server/routes_test.go
  test/routes_test.go
Labels: customer requested, enhancement
